/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrador' at '23/12/16 10:30' with Gradle 2.14.1
 *
 * @author Administrador, @date 23/12/16 10:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
